// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *HttpTransportConfigDetailsTelemetry) setDefaults() {
	{
		val := bool(false)
		s.DisableURLTracking = val
	}
	{
		val := bool(false)
		s.DisableRouterMetrics = val
	}
}

// setDefaults set default value of fields.
func (s *StackContainerConfigDeploy) setDefaults() {
	{
		val := StackContainerConfigDeployStrategy("first-available")
		s.Strategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TcpTransportConfigDetailsTelemetry) setDefaults() {
	{
		val := bool(false)
		s.DisableRouterMetrics.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UdpTransportConfigDetailsTelemetry) setDefaults() {
	{
		val := bool(false)
		s.DisableRouterMetrics.SetTo(val)
	}
}
