// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *AggregateLogsReqScope) setDefaults() {
	{
		val := int(5)
		s.ContextWindow.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ExportStackReq) setDefaults() {
	{
		val := bool(false)
		s.ResolveOrigins.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RecordTypesLinkedFeaturesWildcard) setDefaults() {
	{
		val := bool(false)
		s.ResolveSubDomains = val
	}
}

// setDefaults set default value of fields.
func (s *StackSpecContainerConfigDeploy) setDefaults() {
	{
		val := StackSpecContainerConfigDeployStrategy("first-available")
		s.Strategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1LbConfigRouterConfig) setDefaults() {
	{
		s.DestinationPrioritization.Null = true
	}
}
