// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *AggregateLogsReqScope) setDefaults() {
	{
		val := int(5)
		s.ContextWindow.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ExportStackReq) setDefaults() {
	{
		val := bool(false)
		s.ResolveOrigins.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RecordTypesLinkedFeaturesWildcard) setDefaults() {
	{
		val := bool(false)
		s.ResolveSubDomains = val
	}
}
