# Automatically fetches the latest API spec (and commits the submodule update) and generates a new client, then tags with a prerelease
name: Generate Prerelease Client

on:
  workflow_dispatch:
jobs:
  generate-and-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.API_SPEC_PAT }}
        submodules: true
        
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: Install Ogen
      run: go install -v github.com/ogen-go/ogen/cmd/ogen@latest
      
    - name: Go Update Ogen
      run: go get github.com/ogen-go/ogen/cmd/ogen@latest
      
    - name: Build Spec
      run: (cd api-spec; npm run build:public && npm run build:internal)

    - name: Generate Client
      run: go generate ./...
    
    - name: Commit changes
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.API_SPEC_PAT }}@github.com/${{ github.repository }}
        git commit -am "Auto generate pre-release client from latest API spec" && git push || echo "No changes to commit"
        
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.65.0 
      env:
        GITHUB_TOKEN: ${{ secrets.API_SPEC_PAT }}
        WITH_V: true
        PRERELEASE: true
